# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingConducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprete', models.CharField(max_length=100)),
                ('ponctualite', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('capacite', models.PositiveSmallIntegerField()),
                ('prix_par_personne', models.CharField(max_length=100)),
                ('marque_voiture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='ville_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ville_arrivee', to='projetpaques2018.Ville'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='ville_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ville_depart', to='projetpaques2018.Ville'),
        ),
        migrations.AddField(
            model_name='ratingconducteur',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur'),
        ),
        migrations.AddField(
            model_name='ratingconducteur',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Trajet'),
        ),
        migrations.AddField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Trajet'),
        ),
    ]
