# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
