# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0002_utilisateur_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('capacite', models.PositiveSmallIntegerField()),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur')),
            ],
        ),
    ]
