# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0003_avion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('prix', models.CharField(max_length=100)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Avion')),
                ('ville_arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ville_arrivee', to='projetpaques2018.Ville')),
                ('ville_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ville_depart', to='projetpaques2018.Ville')),
            ],
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='conducteur',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='ville_arrivee',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='ville_depart',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='trajet',
        ),
        migrations.RemoveField(
            model_name='ratingconducteur',
            name='trajet',
        ),
        migrations.DeleteModel(
            name='Trajet',
        ),
        migrations.AddField(
            model_name='booking',
            name='vol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Vol'),
        ),
        migrations.AddField(
            model_name='ratingconducteur',
            name='vol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Vol'),
        ),
    ]
