# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0004_auto_20180403_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='code_postal',
        ),
    ]
