# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0005_remove_ville_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur'),
        ),
    ]
