# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0006_vol_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nombre_de_places',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
