# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetpaques2018', '0007_booking_nombre_de_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('nombre_de_places', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetpaques2018.Utilisateur')),
                ('vol1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol1', to='projetpaques2018.Vol')),
                ('vol2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol2', to='projetpaques2018.Vol')),
            ],
        ),
    ]
